apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-15T11:07:02Z"
  labels:
    app: gatewayservice
  name: gatewayservice
  namespace: default
  resourceVersion: "11499"
  uid: 032f58cf-b909-49ad-98d9-93e03d747ede
spec:
  clusterIP: 172.20.185.217
  clusterIPs:
  - 172.20.185.217
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: gatewayservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
