apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: gatewayservice
  name: gatewayservice
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gatewayservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gatewayservice
    spec:
      containers:
      - image: ganeshreddy4ongraph/springboot-applications:spring-boot-microservices_gatewayservice
        imagePullPolicy: IfNotPresent
        name: springboot-applications
        ports:
        - containerPort: 9999
          protocol: TCP
        resources: 
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
