resources:
  - spring-boot-microservices_configservice.yaml
  - spring-boot-microservices_registryservice.yaml
  - spring-boot-microservices_counterservice.yaml
  - spring-boot-microservices_gatewayservice.yaml
