apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-16T08:58:33Z"
  labels:
    app: spring-boot-microservices-gatewayservice
  name: spring-boot-microservices-gatewayservice
  namespace: default
  resourceVersion: "21762"
  uid: 07c455ab-2849-4f2b-bbb3-743d4b61d70e
spec:
  clusterIP: 172.20.105.187
  clusterIPs:
  - 172.20.105.187
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: spring-boot-microservices-gatewayservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
