apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: spring-boot-microservices-registryservice
  name: spring-boot-microservices-registryservice
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spring-boot-microservices-registryservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-microservices-registryservice
    spec:
      containers:
      - image: ganeshreddy4ongraph/springboot-applications:spring-boot-microservices_registryservice
        imagePullPolicy: IfNotPresent
        name: springboot-applications
        ports:
        - containerPort: 8761
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
