apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-15T06:23:55Z"
  labels:
    app: spring-boot-microservices-configservice
  name: spring-boot-microservices-configservice
  namespace: default
  resourceVersion: "1077885"
  uid: a3158703-9d0c-4c82-ac46-9a5642389bbc
spec:
  clusterIP: 10.100.142.222
  clusterIPs:
  - 10.100.142.222
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31101
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: spring-boot-microservices-configservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
