apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-03-15T11:12:29Z"
  labels:
    app: spring-boot-microservices-configservice
  name: spring-boot-microservices-configservice
  namespace: default
  resourceVersion: "12497"
  uid: 3192f2b0-7f9f-4583-9d82-67c088f5ba0f
spec:
  clusterIP: 172.20.88.40
  clusterIPs:
  - 172.20.88.40
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: spring-boot-microservices-configservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
